[package]
name = "cargo-docs"
version = "0.1.12"
authors = [
  "Btwiuse Arch <btwiuse@gmail.com>",
]
edition = "2021"
description = "A cargo plugin for serving rust and crate doc locally."
documentation = "https://docs.rs/cargo-docs"
repository = "https://github.com/btwiuse/cargo-docs"
readme = "README.md"
categories = ["development-tools::cargo-plugins"]
license = "MIT"

[lib]
path = "lib.rs"

[[bin]]
name = "cargo-book"
path = "main.rs"

[[bin]]
name = "cargo-docs"
path = "main.rs"

[dependencies]
anyhow = "1"
cargo = "0.60"
cargo-util = "0.1"
clap = { version = "3", features = ["derive", "env"] }
dirs = "4"
futures-util = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
hyper-staticfile = "0.8"
tokio = { version = "1", features = ["full"] }
opener = "0.5"

[badges]
travis-ci = { repository = "btwiuse/cargo-docs", branch = "master" }
maintenance = { status = "experimental" }
