[package]
name = "cargo-docs"
version = "0.1.4"
authors = [
  "Daniel Wagner-Hall <dawagner@gmail.com>",
  "Btwiuse Arch <btwiuse@gmail.com>",
]
edition = "2021"
description = "A cargo plugin for serving crate doc locally."
repository = "https://github.com/btwiuse/cargo-docs"
readme = "README.md"
categories = ["development-tools::cargo-plugins"]
license = "MIT"

[[bin]]
name = "cargo-docs"
path = "main.rs"

[dependencies]
anyhow = "1"
cargo = "0.60"
clap = "2.34"
futures-util = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
hyper-staticfile = "0.8"
tokio = { version = "1", features = ["full"] }

[badges]
travis-ci = { repository = "illicitonion/cargo-serve-doc", branch = "master" }
maintenance = { status = "experimental" }
